"""Cria tabela usuarios

Revision ID: 498c07b3c41e
Revises: 
Create Date: 2025-07-20 02:49:02.898349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498c07b3c41e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.String(length=500), nullable=False),
    sa.Column('dataHora', sa.DateTime(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('mensagem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['mensagem_id'], ['mensagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentarios')
    op.drop_table('mensagens')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
